### ISSUE TITLE
id-remove

### ISSUE THREAD

**Issue by ahadru** [MShafquat/ProvaTori#1]
https://github.com/MShafquat/ProvaTori/blob/a5e1209d30e703704d0a319d08cb0805737563a8/backend/models.py#L22

# Remove ID
maybe __id__ automatically created by python model . So why field __id__ need.
if somehow need __id__ field. explain.

**Comment by MShafquat** [comment]
ID field was created to generate a link to an individual product. Other way was to use product name, but this field may not be unique always,

**Comment by ahadru** [comment]
all model have default __id__ field without defining. so why you are redefining again.

**Comment by MShafquat** [comment]
If you are sure, then remove it.
